import ProjectDescription

let workspace = Workspace(
    name: "ExampleApp",
    projects: ["**"],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: true,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
